# Generated by Django 3.2.2 on 2023-01-11 10:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230109_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('vendor', 'Vendor')], max_length=255, verbose_name='role'),
        ),
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('store_name', models.CharField(max_length=250, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='store_logos')),
                ('store_desc', models.TextField()),
                ('num_of_employee', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=100)),
                ('line_1', models.TextField()),
                ('line_2', models.TextField(blank=True, null=True)),
                ('zip_code', models.CharField(max_length=50)),
                ('cac_num', models.CharField(max_length=50)),
                ('cac_doc', models.FileField(upload_to='cac_documents')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreBankDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_name', models.CharField(max_length=300)),
                ('account_num', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(10, 'the field must contain at least 10 characters')])),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10, 'the field must contain at least 12 characters')])),
                ('bank_branch', models.CharField(max_length=300)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('store', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to='accounts.storeprofile')),
            ],
        ),
    ]
