# Generated by Django 3.2.2 on 2023-02-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_moduleaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sent_vendor_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='vendor_status',
            field=models.CharField(blank=True, choices=[('applied', 'applied'), ('approved', 'approved'), ('unapproved', 'unapproved'), ('blocked', 'blocked')], max_length=250, null=True),
        ),
    ]
