# Generated by Django 3.2.2 on 2023-01-11 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230111_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprofile',
            name='cac_doc',
            field=models.FileField(upload_to='cac_documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='logo',
            field=models.ImageField(blank=True, upload_to='store_logos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
