# Generated by Django 3.2.2 on 2023-03-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_favourite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_dashboard', 'Can view all dashboards')]},
        ),
    ]
