# Generated by Django 3.2.2 on 2023-03-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(choices=[('email', 'email'), ('google', 'google')], default='email', max_length=255, verbose_name='provider'),
        ),
    ]
