# Generated by Django 4.1 on 2023-07-07 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprofile',
            name='cac_doc',
            field=models.FileField(null=True, upload_to='cac_documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'jpg', 'jpeg'])]),
        ),
    ]
