# Generated by Django 4.1 on 2023-08-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_referral_code_user_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_bonus',
            field=models.FloatField(default=0),
        ),
    ]
