# Generated by Django 3.2.2 on 2023-02-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='battery_cap',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='battery_type',
            field=models.CharField(choices=[('Tubular', 'Tubular'), ('lithium', 'Lithium')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_power',
            field=models.FloatField(null=True),
        ),
    ]
