# Generated by Django 3.2.2 on 2023-02-07 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_amount_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='battery_cap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='battery_type',
            field=models.CharField(blank=True, choices=[('Tubular', 'Tubular'), ('lithium', 'Lithium')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='main.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_power',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
