# Generated by Django 3.2.2 on 2023-02-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230207_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='address',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='address2',
        ),
    ]
