# Generated by Django 3.2.2 on 2023-01-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230120_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='installation',
            new_name='installation_fee',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping',
            new_name='shipping_fee',
        ),
        migrations.AlterField(
            model_name='order',
            name='booking_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
