# Generated by Django 3.2.2 on 2023-02-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230210_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
