# Generated by Django 3.2.2 on 2023-02-10 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_paymentdetail_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid_for',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('completed', 'completed')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to=settings.AUTH_USER_MODEL),
        ),
    ]
