# Generated by Django 3.2.2 on 2023-02-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230210_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('specta', 'Specta'), ('outright', 'Outright'), ('lease', 'Lease To Own'), ('power-as-a-service', 'Power as a service')], max_length=300, null=True),
        ),
    ]
