# Generated by Django 3.2.2 on 2023-02-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='locations',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='accepted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivered_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='processed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
