# Generated by Django 3.2.2 on 2023-02-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_deliverydetail_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_fee',
            field=models.FloatField(default=0),
        ),
    ]
