# Generated by Django 3.2.2 on 2023-02-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_orderitem_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='accepted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivered_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='processed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
