# Generated by Django 3.2.2 on 2023-02-17 10:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20230216_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetail',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
