# Generated by Django 3.2.2 on 2023-02-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_deliverydetail_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='locations',
        ),
    ]
