# Generated by Django 3.2.2 on 2023-02-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20230221_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='locations',
        ),
    ]
