# Generated by Django 3.2.2 on 2023-02-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_product_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='locations',
            field=models.ManyToManyField(blank=True, to='main.DeliveryDetail'),
        ),
    ]
