# Generated by Django 3.2.2 on 2023-02-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_product_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='accepted_at',
            new_name='in_transit_at',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('processing', 'processing'), ('in-transit', 'in-transit'), ('delivered', 'delivered'), ('user-canceled', 'user-canceled')], default='pending', max_length=255),
        ),
    ]
