# Generated by Django 3.2.2 on 2023-03-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_commission_payouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='installation_fee',
            field=models.FloatField(default=0),
        ),
    ]
