# Generated by Django 3.2.2 on 2023-03-01 15:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20230301_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='battery_cap',
            new_name='battery_cap_AH',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='total_power',
            new_name='battery_voltage',
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='key_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='total_power_kva',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.TextField(blank=True, null=True),
        ),
    ]
