# Generated by Django 3.2.2 on 2023-03-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20230301_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.CharField(choices=[('NW', 'NW'), ('NE', 'NE'), ('NC', 'NC'), ('SW', 'SW'), ('SE', 'SE'), ('SS', 'SS')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='NC_delivery_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='NE_delivery_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='NW_delivery_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='SE_delivery_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='SS_delivery_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='SW_delivery_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='disclaimer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ships_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='locations',
            field=models.ManyToManyField(blank=True, to='main.Location'),
        ),
        migrations.DeleteModel(
            name='DeliveryDetail',
        ),
    ]
