# Generated by Django 3.2.2 on 2023-03-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20230302_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='locations',
            field=models.ManyToManyField(blank=True, to='main.Location'),
        ),
    ]
