# Generated by Django 3.2.2 on 2023-03-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_orderitem_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('declined', 'declined')], default='pending', max_length=20),
        ),
    ]
