# Generated by Django 3.2.2 on 2023-03-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20230309_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='installed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
