# Generated by Django 3.2.2 on 2023-03-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_orderitem_installed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('processing', 'processing'), ('in-transit', 'in-transit'), ('delivered', 'delivered'), ('installed', 'installed'), ('cancel-requested', 'cancel-requested'), ('user-canceled', 'user-canceled')], default='pending', max_length=255),
        ),
    ]
