# Generated by Django 3.2.2 on 2023-03-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ships_from',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('verified', 'verified'), ('unapproved', 'unapproved')], default='pending', max_length=100),
        ),
    ]
