# Generated by Django 3.2.2 on 2023-03-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20230310_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ships_from',
            field=models.ManyToManyField(blank=True, related_name='product_ships_from', to='main.Location'),
        ),
    ]
