# Generated by Django 3.2.2 on 2023-03-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_product_ships_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('power_kw', models.FloatField()),
                ('avg_hr_per_day', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
