# Generated by Django 3.2.2 on 2023-03-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_calculatoritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='battery_type',
            field=models.CharField(blank=True, choices=[('Tubular', 'Tubular'), ('Lithium', 'Lithium'), ('Dry cell (SMF)', 'Dry cell (SMF)')], max_length=255, null=True),
        ),
    ]
