# Generated by Django 3.2.2 on 2023-03-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20230316_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='warranty',
        ),
    ]
