# Generated by Django 3.2.2 on 2023-03-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_remove_product_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
