# Generated by Django 3.2.2 on 2023-03-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_product_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payouts',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('processing', 'processing')], default='pending', max_length=255),
        ),
    ]
