# Generated by Django 3.2.2 on 2023-03-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_payouts_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('cancel-requested', 'cancel-requested'), ('canceled', 'canceled')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('processing', 'processing'), ('in-transit', 'in-transit'), ('delivered', 'delivered'), ('installed', 'installed'), ('cancel-requested', 'cancel-requested'), ('canceled', 'canceled')], default='pending', max_length=255),
        ),
    ]
