# Generated by Django 3.2.2 on 2023-04-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_termandcondition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculatoritem',
            old_name='power_kw',
            new_name='power',
        ),
    ]
