# Generated by Django 3.2.2 on 2023-04-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_bankdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankDetail',
            new_name='Bank',
        ),
    ]
