# Generated by Django 3.2.2 on 2023-04-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20230419_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='crm_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
