# Generated by Django 3.2.2 on 2023-04-25 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_supportticket_crm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='categories', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
