# Generated by Django 4.1 on 2023-05-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_alter_productcategory_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(choices=[('testimonials', 'testimonials'), ('user_education_videos', 'user_education_videos')], max_length=50)),
                ('file_name', models.CharField(max_length=50)),
                ('url', models.URLField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
