# Generated by Django 4.1 on 2023-05-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file_name',
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
