# Generated by Django 4.1 on 2023-05-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_remove_video_file_name_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='testifier_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='testifier_occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_excerpt',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
