# Generated by Django 4.1 on 2023-05-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_video_testifier_name_video_testifier_occupation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_excerpt',
            new_name='desc',
        ),
    ]
