# Generated by Django 4.1 on 2023-07-11 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0067_rename_video_excerpt_video_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('eligible_amount', models.FloatField()),
                ('paid_amount', models.FloatField()),
                ('transaction_id', models.CharField(max_length=255)),
                ('payment_channel', models.CharField(default='flutterwave', max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='balance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.paymentbalance'),
        ),
    ]
