# Generated by Django 4.1 on 2023-07-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_paymentbalance_paymentdetail_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbalance',
            name='spectaID',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
