# Generated by Django 4.1 on 2023-07-14 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_paymentbalance_spectaid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentbalance',
            old_name='eligible_amount',
            new_name='total_amount',
        ),
    ]
