# Generated by Django 4.1 on 2023-07-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_rename_eligible_amount_paymentbalance_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentbalance',
            old_name='spectaID',
            new_name='spectaId',
        ),
    ]
