# Generated by Django 4.1 on 2023-08-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_alter_paymentbalance_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_first_order',
            field=models.BooleanField(null=True),
        ),
    ]
